### PR TITLE
Important missing and min-width irrelevant.

### PR DESCRIPTION
**Pull request by martinmarsicano**
Fix of #80 
With this https://github.com/OWASP/owasp.github.io/issues/16 gets fixed

### CODE REVIEW

**Comment by martinmarsicano** [comment]
@kingthorin this one?

**Review by kingthorin — APPROVED** [review]
Seems reasonable to me

**Comment by kingthorin** [comment]
Nope I can really only do www-community outside of projects I’m directly leading (zap, wstg, vwad).

**Comment by martinmarsicano** [comment]
Ok, thanks!. Will wait for @hblankenship or anyone who can

**Comment by kingthorin** [comment]
@martinmarsicano for the future you can automatically close issues on PR merge using keywords:
https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

In this case if you’d left out “of” it would have closed 😉

**Comment by martinmarsicano** [comment]
Yes, as I wasn't the one that added the issue and I couldn't replicate Björn screenshot, I left it open so they can test if it was fixed.

**Comment by kingthorin** [comment]
Okay, no problem

**Pull request merged**
