### PR TITLE
Update header.html

### PR DESCRIPTION
**Pull request by victoriadrake**
Hook up "Join" button.

### CODE REVIEW

**Comment by victoriadrake** [comment]
The conflicting lines disagree on absolute and relative URLs:

```html
<<<<<<< patch-1
          <a href="https://www2.owasp.org/donate?reponame={{ site.github.repository_name }}{{ pagetitle }}" class="cta-button green">Donate</a>
          <a href="https://www2.owasp.org/membership" class="cta-button">Join</a>
=======
          <a href="/donate?reponame={{ site.github.repository_name }}{{ pagetitle }}" class="cta-button green">Donate</a>
          <a href="/membership" class="cta-button">Join</a>
>>>>>>> master
```

I think the correct choice hinges on whether the domain name (`https://www2.owasp.org/ `) is likely to change.

**Comment by kingthorin** [comment]
`www2` was a placeholder while the wiki was still on `www` and the migration was happening (it still resolves, but I doubt it's meant to be kept long term). Now that the switch has been made `www2` is definitely not necessary. However, I don't know if it should include `www`.

Going with the relative version takes the domain out of the question, which seems kinda handy to me :wink: (Also kinda makes the question and wondering go away.)

**Comment by victoriadrake** [comment]
Relative links would be my preference too, just from general good principles. Before that though I would argue for consistency with the rest of the site theme. Better practice or not, it will only create confusion if we use relative links in one place and absolute links everywhere else.

So I open up the general question for the theme as a whole: relative or absolute?

**Comment by mikemccamon** [comment]
This issue has been resolved with relative paths following the full launch of website and DNS fix for www. and wiki.

**Pull request closed without merging**
