### PR TITLE
add alt tag for image

### PR DESCRIPTION
**Pull request by lpmi-13**
this was affecting the lighthouse audit score for accessibility.

### CODE REVIEW

**Comment by kingthorin** [comment]
As the event is now over and the file is conflicting I think this PR can be closed.

**Comment by lpmi-13** [comment]
I can address any conflicts in a few hours...is the same banner.html going to be used for next year? If so, might be good to add in the alt tag now so its ready to go.

**Comment by kingthorin** [comment]
I have no idea if it’ll be re-used. I believe the org kinda uses it on a rotational manner, ex: it already has new content (this time without an image).

**Comment by lpmi-13** [comment]
Fair enough. Will close.

**Comment by kingthorin** [comment]
Thanks, for the contribution. Please don't let this discouage you from helping on other fronts.

**Pull request closed without merging**
